INSERT INTO EXCHANGE_VALUE(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO,PORT) VALUES(1001,65,'USD','INR',0);
INSERT INTO EXCHANGE_VALUE(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO,PORT) VALUES(1002,80,'EUR','INR',0);
INSERT INTO EXCHANGE_VALUE(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO,PORT) VALUES(1003,50,'AUD','INR',0);
INSERT INTO EXCHANGE_VALUE(ID,CONVERSION_MULTIPLE,CURRENCY_FROM,CURRENCY_TO,PORT) VALUES(1004,100,'POUND','INR',0);